/*! SeaJS 2.0.0 | seajs.org/LICENSE.md */
(function(m,s){function y(a){return function(b){return Object.prototype.toString.call(b)==="[object "+a+"]"}}function H(a){return a.match(ja)[0]}function Q(a){a=a.replace(ka,"/");for(a=a.replace(la,"$1/");a.match(R);)a=a.replace(R,"/");return a}function S(a){a=Q(a);ma.test(a)?a=a.slice(0,-1):na.test(a)||(a+=".js");return a.replace(":80/","/")}function oa(a){var b=h.vars;b&&-1<a.indexOf("{")&&(a=a.replace(pa,function(a,d){return I(b[d])?b[d]:a}));return a}function T(a,b){return qa.test(a)?a:ra.test(a)?
H(b||v)+a:sa.test(a)?(v.match(ta)||["/"])[0]+a.substring(1):h.base+a}function J(a,b){if(!a)return"";var c=a,d=h.alias,c=a=d&&I(d[c])?d[c]:c,d=h.paths,e;d&&((e=c.match(ua))&&I(d[e[1]]))&&(c=d[e[1]]+e[2]);a=oa(c);a=T(a,b);e=a=S(a);var c=h.map,f=e;if(c)for(d=0;d<c.length&&(f=c[d],f=w(f)?f(e)||e:e.replace(f[0],f[1]),f===e);d++);return f}function va(a,b,c){var d=U.test(a),e=n.createElement(d?"link":"script");c&&(c=w(c)?c(a):c)&&(e.charset=c);wa(e,b,d);d?(e.rel="stylesheet",e.href=a):(e.async=!0,e.src=
a);z=e;V?x.insertBefore(e,V):x.appendChild(e);z=s}function wa(a,b,c){!c||!W&&"onload"in a?a.onload=a.onerror=a.onreadystatechange=function(){var d=a.readyState;xa.test(d)&&(a.onload=a.onerror=a.onreadystatechange=null,c||h.debug||x.removeChild(a),a=s,"loaded"==d?setTimeout(b,1):b())}:setTimeout(function(){X(a,b)},1)}function X(a,b){var c=a.sheet,d;if(W)c&&(d=!0);else if(c)try{c.cssRules&&(d=!0)}catch(e){"NS_ERROR_DOM_SECURITY_ERR"===e.name&&(d=!0)}setTimeout(function(){d?b():X(a,b)},20)}function ya(){if(z)return z;
if(A&&"interactive"===A.readyState)return A;for(var a=x.getElementsByTagName("script"),b=a.length-1;0<=b;b--){var c=a[b];if("interactive"===c.readyState)return A=c}}function za(a){var b=[];a.replace(Aa,"").replace(Ba,function(a,d,e){e&&b.push(e)});return b}function B(a){this.uri=a;this.dependencies=[];this.exports=null;this.status=0}function t(a,b){if(C(a)){for(var c=[],d=0;d<a.length;d++)c[d]=t(a[d],b);return c}c={id:a,refUri:b};p("resolve",c);return c.uri||J(c.id,b)}function D(a,b){C(a)||(a=[a]);
Y(a,function(){for(var c=[],d=0;d<a.length;d++)c[d]=Z(k[a[d]]);b&&b.apply(m,c)})}function Y(a,b){var c=$(a);if(0===c.length)b();else{p("load",c);for(var d=c.length,e=d,f=0;f<d;f++)(function(a){function c(b){b||(b=d);var e=$(f.dependencies);0===e.length?b():aa(f)?(e=q,e.push(e[0]),ba("Circular dependencies: "+e.join(" -> ")),q.length=0,b(!0)):(ca[a]=e,Y(e,b))}function d(a){!a&&f.status<K&&(f.status=K);0===--e&&b()}var f=k[a];f.dependencies.length?c(function(b){function c(){d(b)}f.status<E?da(a,c):
c()}):f.status<E?da(a,c):d()})(c[f])}}function da(a,b){function c(){delete L[e];M[e]=!0;F&&(ea(a,F),F=s);var b,c=G[e];for(delete G[e];b=c.shift();)b()}k[a].status=Ca;var d={uri:a};p("fetch",d);var e=d.requestUri||a;if(M[e])b();else if(L[e])G[e].push(b);else{L[e]=!0;G[e]=[b];var f=h.charset;p("request",d={uri:a,requestUri:e,callback:c,charset:f});d.requested||va(d.requestUri,c,f)}}function N(a,b,c){1===arguments.length&&(c=a,a=s);!C(b)&&w(c)&&(b=za(c.toString()));var d={id:a,uri:t(a),deps:b,factory:c};
if(!d.uri&&n.attachEvent){var e=ya();e?d.uri=e.src:ba("Failed to derive: "+c)}p("define",d);d.uri?ea(d.uri,d):F=d}function ea(a,b){var c=k[a]||(k[a]=new B(a));c.status<E&&(c.id=b.id||a,c.dependencies=t(b.deps||[],a),c.factory=b.factory,c.factory!==s&&(c.status=E))}function Da(a){function b(b){return t(b,a.uri)}function c(a){return Z(k[b(a)])}if(!a)return null;if(a.status>=fa)return a.exports;a.status=fa;c.resolve=b;c.async=function(a,d){D(b(a),d);return c};var d=a.factory,d=w(d)?d(c,a.exports={},
a):d;a.exports=d===s?a.exports:d;a.status=Ea;return a.exports}function $(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];d&&(k[d]||(k[d]=new B(d))).status<K&&b.push(d)}return b}function Z(a){var b=Da(a);null!==b||a&&U.test(a.uri)||p("error",a);return b}function aa(a){var b=ca[a.uri]||[];if(0===b.length)return!1;q.push(a.uri);a:{for(a=0;a<b.length;a++)for(var c=0;c<q.length;c++)if(q[c]===b[a]){a=!0;break a}a=!1}if(a){a=q[0];for(c=b.length-1;0<=c;c--)if(b[c]===a){b.splice(c,1);break}return!0}for(a=0;a<
b.length;a++)if(aa(k[b[a]]))return!0;q.pop();return!1}function ga(a){var b=h.preload,c=b.length;c?D(t(b),function(){b.splice(0,c);ga(a)}):a()}function O(a){for(var b in a){var c=a[b];if(c&&"plugins"===b){b="preload";for(var d=[],e=void 0;e=c.shift();)d.push(ha+"plugin-"+e);c=d}if((d=h[b])&&Fa(d))for(var g in c)d[g]=c[g];else C(d)?c=d.concat(c):"base"===b&&(c=S(T(c+"/"))),h[b]=c}p("config",a);return f}var l=m.seajs;if(!l||!l.version){var f=m.seajs={version:"2.0.0"},Fa=y("Object"),I=y("String"),C=Array.isArray||
y("Array"),w=y("Function"),ba=f.log=function(a,b){m.console&&(b||h.debug)&&console[b||(b="log")]&&console[b](a)},u=f.events={};f.on=function(a,b){if(!b)return f;(u[a]||(u[a]=[])).push(b);return f};f.off=function(a,b){if(!a&&!b)return f.events=u={},f;var c=u[a];if(c)if(b)for(var d=c.length-1;0<=d;d--)c[d]===b&&c.splice(d,1);else delete u[a];return f};var p=f.emit=function(a,b){var c=u[a],d;if(c)for(c=c.slice();d=c.shift();)d(b);return f},ja=/[^?#]*\//,ka=/\/\.\//g,la=/([^:\/])\/\/+/g,R=/\/[^/]+\/\.\.\//g,
na=/\?|\.(?:css|js)$|\/$/,ma=/#$/,ua=/^([^/:]+)(\/.+)$/,pa=/{([^{]+)}/g,qa=/:\//,ra=/^\./,sa=/^\//,ta=/^.*?\/\/.*?\//,n=document,ia=location,v=H(ia.href),r=n.getElementsByTagName("script"),g=n.getElementById("seajsnode")||r[r.length-1],ha=H(g.hasAttribute?g.src:g.getAttribute("src",4))||v;f.cwd=function(a){return a?v=Q(a+"/"):v};var x=n.getElementsByTagName("head")[0]||n.documentElement,V=x.getElementsByTagName("base")[0],U=/\.css(?:\?|$)/i,xa=/^(?:loaded|complete|undefined)$/,z,A,W=536>1*navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,
"$1"),Ba=/"(?:\\"|[^"])*"|'(?:\\'|[^'])*'|\/\*[\S\s]*?\*\/|\/(?:\\\/|[^/\r\n])+\/(?=[^\/])|\/\/.*|\.\s*require|(?:^|[^$])\brequire\s*\(\s*(["'])(.+?)\1\s*\)/g,Aa=/\\\\/g,k=f.cache={},F,L={},M={},G={},ca={},Ca=1,E=2,K=3,fa=4,Ea=5;B.prototype.destroy=function(){delete k[this.uri];delete M[this.uri]};var q=[];f.use=function(a,b){ga(function(){D(t(a),b)});return f};B.load=D;f.resolve=J;f.define=N;var P=m.define;m.define=P?function(){w(P)&&P.apply(m,arguments);N.apply(m,arguments)}:N;f.require=function(a){return(k[J(a)]||
{}).exports};var h=O.data={base:function(){var a=ha,b=a.match(/^(.+?\/)(?:seajs\/)+(?:\d[^/]+\/)?$/);b&&(a=b[1]);return a}(),charset:"utf-8",preload:[]};f.config=O;O({plugins:function(){var a,b=ia.search.replace(/(seajs-\w+)(&|$)/g,"$1=1$2"),b=b+(" "+n.cookie);b.replace(/seajs-(\w+)=1/g,function(b,d){(a||(a=[])).push(d)});return a}()});r=g.getAttribute("data-config");g=g.getAttribute("data-main");r&&h.preload.push(r);g&&f.use(g);if(l&&l.args)for(r=["define","config","use"],l=l.args,g=0;g<l.length;g+=
2)f[r[l[g]]].apply(f,l[g+1])}})(this);
